version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the path-filtering orb is required to continue a pipeline based on
# the path of an updated fileset
# orbs:
#   path-filtering: circleci/path-filtering@0.1.1
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Run .circleci/main.yml with specific parameters
          command: |
            echo '{ "further": true }' > /home/circleci/parameters.json
      - continuation/continue:
          configuration_path: .circleci/main.yml
          parameters: /home/circleci/parameters.json


workflows:
  setup:
    jobs:
      - setup