version: 2.1

executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:20.5.0

jobs:  
  test-job-1:
    executor: node
    steps:
      - checkout
      - run: echo "Running test-job-1"
      

workflows:
  workflow1:
    jobs:
      - test-job-1
