version: 2.1

executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:20.5.0

jobs:  
  notify-slack:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: echo "Notifying Slack"


workflows:
  run-stuff:
    jobs:
      - notify-slack

