version: 2.1

orbs:
  slack: circleci/slack@4.12.6

executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:20.5.0

jobs:  
  notify-slack:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: echo "Notifying Slack"
      - slack/notify:
          custom: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "🏁 Run finished"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "View Job in CircleCI"
                        },
                        "url": "https://google.com",
                        "action_id": "button-action"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "plain_text",
                          "text": "Run Duration: 9m 40s"
                        }
                      ]
                    },
                    {
                      "type": "rich_text",
                      "elements": [
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "Project:",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": " Planable-app-visual\n"
                            },
                            {
                              "type": "text",
                              "text": "Branch:",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": " fix/P-7125-tooltip\n"
                            },
                            {
                              "type": "text",
                              "text": "Commit: ",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "emoji",
                              "name": "ladybug",
                              "unicode": "1f41e"
                            },
                            {
                              "type": "text",
                              "text": " Isolate the css fix\n\n"
                            },
                            {
                              "type": "text",
                              "text": "Overall Tests: 120",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": "\n"
                            },
                            {
                              "type": "emoji",
                              "name": "large_green_circle",
                              "unicode": "1f7e2",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": " Passed: 95",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": "\n"
                            },
                            {
                              "type": "emoji",
                              "name": "white_circle",
                              "unicode": "26aa",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": "️ Ignored: 5",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": "\n"
                            },
                            {
                              "type": "emoji",
                              "name": "red_circle",
                              "unicode": "1f534",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": " Failed: 15",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": "\n"
                            },
                            {
                              "type": "emoji",
                              "name": "large_purple_circle",
                              "unicode": "1f7e3",
                              "style": {
                                "bold": true
                              }
                            },
                            {
                              "type": "text",
                              "text": " Flaky: 5",
                              "style": {
                                "bold": true
                              }
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "type": "divider"
                    }
                  ]
                }
              ]
            }
          event: always


workflows:
  run-stuff:
    jobs:
      - notify-slack:
          context: SLACK
    

