version: 2.1

orbs:
  slack: circleci/slack@4.12.6

executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:20.5.0

jobs:  
  notify-slack:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: echo "Notifying Slack"
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always


workflows:
  run-stuff:
    jobs:
      - notify-slack:
          context: SLACK
    

