version: 2.1

parameters:
  further:
    type: boolean
    default: false

executors:
  node:
    resource_class: small
    docker:
      - image: cimg/node:20.5.0

jobs:  
  test-job-1:
    executor: node
    steps:
      - checkout
      - run: echo "Running test-job-1"
  test-job-2:
    executor: node
    steps:
      - checkout
      - run: echo "Running test-job-2"
      

workflows:
  somethingElse1:
    when: << pipeline.parameters.further >>
    jobs:
      - test-job-1
  somethingElse2:
    when: 
      equal:  [false, << pipeline.parameters.further >>]
    jobs:
      - test-job-2